# Generated by Django 4.0.1 on 2022-01-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_comment_rating_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['user', 'hotel']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
