# Generated by Django 4.0.1 on 2022-01-17 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0010_alter_comment_options_rename_author_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('hotel', 'user')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
    ]
