# Generated by Django 4.0.1 on 2022-01-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_rename_author_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
    ]
